---
version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - gosec
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    presets:
      - std-error-handling
formatters:
  enable:
    - gofmt
    - gofumpt
