// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Support",
            "url": "https://github.com/lsst-dm/deliverator"
        },
        "license": {
            "name": "GPL-3.0",
            "url": "https://www.gnu.org/licenses/gpl-3.0.en.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/upload": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "uploads"
                ],
                "summary": "upload file to S3",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Destination S3 URI",
                        "name": "uri",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "path to file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "arbitrary string to include in logs",
                        "name": "slug",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/requestStatus200"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/requestStatus400"
                        },
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/requestStatus404"
                        },
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/requestStatus408"
                        },
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/requestStatus500"
                        },
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    },
                    "504": {
                        "description": "Gateway Timeout",
                        "schema": {
                            "$ref": "#/definitions/requestStatus504"
                        },
                        "headers": {
                            "X-Error": {
                                "type": "string",
                                "description": "error message"
                            }
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "report service version and configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/VersionInfo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "VersionInfo": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "version": {
                    "type": "string",
                    "example": "0.0.0"
                }
            }
        },
        "requestStatus200": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "msg": {
                    "type": "string",
                    "example": "upload succeeded"
                },
                "task": {
                    "$ref": "#/definitions/task"
                }
            }
        },
        "requestStatus400": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "msg": {
                    "type": "string",
                    "example": "error parsing request: missing field: uri"
                },
                "task": {
                    "type": "object",
                    "properties": {
                        "duration": {
                            "type": "string",
                            "example": "37.921µs"
                        },
                        "file": {
                            "type": "string",
                            "example": "/path/to/file.txt"
                        },
                        "id": {
                            "type": "string",
                            "format": "uuid"
                        },
                        "slug": {
                            "description": "for logging",
                            "type": "string",
                            "example": "Gray Garden Slug"
                        }
                    }
                }
            }
        },
        "requestStatus404": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 404
                },
                "msg": {
                    "type": "string",
                    "example": "upload failed because the bucket does not exist"
                },
                "task": {
                    "$ref": "#/definitions/task"
                }
            }
        },
        "requestStatus408": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 408
                },
                "msg": {
                    "type": "string",
                    "example": "upload queue timeout"
                },
                "task": {
                    "$ref": "#/definitions/task"
                }
            }
        },
        "requestStatus500": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "msg": {
                    "type": "string",
                    "example": "unknown error"
                },
                "task": {
                    "type": "object",
                    "properties": {
                        "attempts": {
                            "type": "integer",
                            "example": 5
                        },
                        "duration": {
                            "type": "string",
                            "example": "37.921µs"
                        },
                        "duration_seconds": {
                            "type": "number",
                            "example": 0.021
                        },
                        "file": {
                            "type": "string",
                            "example": "/path/to/file.txt"
                        },
                        "id": {
                            "type": "string",
                            "format": "uuid"
                        },
                        "size_bytes": {
                            "type": "integer",
                            "example": 1000
                        },
                        "slug": {
                            "description": "for logging",
                            "type": "string",
                            "example": "Gray Garden Slug"
                        },
                        "transfer_rate": {
                            "description": "human friendly",
                            "type": "string",
                            "example": "1000B/s"
                        },
                        "transfer_rate_mbits": {
                            "type": "number",
                            "example": 0.001
                        },
                        "upload_parts": {
                            "type": "integer",
                            "example": 1
                        },
                        "uri": {
                            "type": "string",
                            "example": "s3://my-bucket/my-key"
                        }
                    }
                }
            }
        },
        "requestStatus504": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 504
                },
                "msg": {
                    "type": "string",
                    "example": "timeout during upload attempt 2/2"
                },
                "task": {
                    "type": "object",
                    "properties": {
                        "duration": {
                            "type": "string",
                            "example": "56.115µs"
                        },
                        "file": {
                            "type": "string",
                            "example": "/path/to/file.txt"
                        },
                        "id": {
                            "type": "string",
                            "format": "uuid"
                        },
                        "slug": {
                            "description": "for logging",
                            "type": "string",
                            "example": "Gray Garden Slug"
                        },
                        "uri": {
                            "type": "string",
                            "example": "s3://my-bucket/my-key"
                        }
                    }
                }
            }
        },
        "task": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer",
                    "example": 1
                },
                "duration": {
                    "description": "human friendly",
                    "type": "string",
                    "example": "21.916462ms"
                },
                "duration_seconds": {
                    "type": "number",
                    "example": 0.021
                },
                "file": {
                    "type": "string",
                    "example": "/path/to/file.txt"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "size_bytes": {
                    "type": "integer",
                    "example": 1000
                },
                "slug": {
                    "description": "for logging",
                    "type": "string",
                    "example": "Gray Garden Slug"
                },
                "transfer_rate": {
                    "description": "human friendly",
                    "type": "string",
                    "example": "1000B/s"
                },
                "transfer_rate_mbits": {
                    "type": "number",
                    "example": 0.001
                },
                "upload_parts": {
                    "type": "integer",
                    "example": 1
                },
                "uri": {
                    "type": "string",
                    "example": "s3://my-bucket/my-key"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "s3nd|The Deliverator API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
