definitions:
  VersionInfo:
    properties:
      config:
        additionalProperties:
          type: string
        type: object
      version:
        example: 0.0.0
        type: string
    type: object
  requestStatus200:
    properties:
      code:
        example: 200
        type: integer
      msg:
        example: upload succeeded
        type: string
      task:
        $ref: '#/definitions/task'
    type: object
  requestStatus400:
    properties:
      code:
        example: 400
        type: integer
      msg:
        example: 'error parsing request: missing field: uri'
        type: string
      task:
        properties:
          file:
            example: /path/to/file.txt
            type: string
          id:
            format: uuid
            type: string
          slug:
            description: for logging
            example: Gray Garden Slug
            type: string
        type: object
    type: object
  requestStatus404:
    properties:
      code:
        example: 404
        type: integer
      msg:
        example: upload failed because the bucket does not exist
        type: string
      task:
        $ref: '#/definitions/task'
    type: object
  requestStatus408:
    properties:
      code:
        example: 408
        type: integer
      msg:
        example: upload queue timeout
        type: string
      task:
        $ref: '#/definitions/task'
    type: object
  requestStatus500:
    properties:
      code:
        example: 500
        type: integer
      msg:
        example: unknown error
        type: string
      task:
        properties:
          attempts:
            example: 5
            type: integer
          file:
            description: request input
            example: /path/to/file.txt
            type: string
          id:
            format: uuid
            type: string
          slug:
            description: request input; for logging
            example: Gray Garden Slug
            type: string
          upload_attempts:
            example: 1
            type: integer
          upload_parts:
            example: 1
            type: integer
          upload_queued_seconds:
            example: 0.021
            type: number
          upload_rate:
            description: human friendly
            example: 42Mbit/s
            type: string
          upload_rate_bytes:
            example: 796.178343
            type: number
          upload_size_bytes:
            example: 1000
            type: integer
          upload_total:
            description: human friendly
            example: 21.916462ms
            type: string
          upload_total_seconds:
            example: 1.255
            type: number
          upload_transfer_seconds:
            example: 1.234
            type: number
          uri:
            description: request input
            example: s3://my-bucket/my-key
            type: string
        type: object
    type: object
  requestStatus504:
    properties:
      code:
        example: 504
        type: integer
      msg:
        example: timeout during upload attempt 2/2
        type: string
      task:
        properties:
          file:
            example: /path/to/file.txt
            type: string
          id:
            format: uuid
            type: string
          slug:
            description: for logging
            example: Gray Garden Slug
            type: string
          uri:
            example: s3://my-bucket/my-key
            type: string
        type: object
    type: object
  task:
    properties:
      file:
        description: request input
        example: /path/to/file.txt
        type: string
      id:
        format: uuid
        type: string
      slug:
        description: request input; for logging
        example: Gray Garden Slug
        type: string
      upload_attempts:
        example: 1
        type: integer
      upload_parts:
        example: 1
        type: integer
      upload_queued_seconds:
        example: 0.021
        type: number
      upload_rate:
        description: human friendly
        example: 42Mbit/s
        type: string
      upload_rate_bytes:
        example: 796.178343
        type: number
      upload_size_bytes:
        example: 1000
        type: integer
      upload_total:
        description: human friendly
        example: 21.916462ms
        type: string
      upload_total_seconds:
        example: 1.255
        type: number
      upload_transfer_seconds:
        example: 1.234
        type: number
      uri:
        description: request input
        example: s3://my-bucket/my-key
        type: string
    type: object
info:
  contact:
    name: Support
    url: https://github.com/lsst-dm/deliverator
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  title: s3nd|The Deliverator API
  version: 0.0.0
paths:
  /upload:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Destination S3 URI
        in: formData
        name: uri
        required: true
        type: string
      - description: path to file to upload
        in: formData
        name: file
        required: true
        type: string
      - description: arbitrary string to include in logs
        in: formData
        name: slug
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/requestStatus200'
        "400":
          description: Bad Request
          headers:
            X-Error:
              description: error message
              type: string
          schema:
            $ref: '#/definitions/requestStatus400'
        "404":
          description: Not Found
          headers:
            X-Error:
              description: error message
              type: string
          schema:
            $ref: '#/definitions/requestStatus404'
        "408":
          description: Request Timeout
          headers:
            X-Error:
              description: error message
              type: string
          schema:
            $ref: '#/definitions/requestStatus408'
        "500":
          description: Internal Server Error
          headers:
            X-Error:
              description: error message
              type: string
          schema:
            $ref: '#/definitions/requestStatus500'
        "504":
          description: Gateway Timeout
          headers:
            X-Error:
              description: error message
              type: string
          schema:
            $ref: '#/definitions/requestStatus504'
      summary: upload file to S3
      tags:
      - uploads
  /version:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/VersionInfo'
      summary: report service version and configuration
      tags:
      - version
swagger: "2.0"
